machines:

  - name: backend
    disk:
      cloud_image:
        name: ubuntu_18_04
    interfaces:
      - bridge: br0
    run_script: ./backend.sh

  - name: emulated
    memory_mb: 8182
    cpus: 4
    disk:
      cloud_image:
        name: ubuntu_18_04
        expand_gigabytes: 25
    interfaces:
      - bridge: br0
    run_script: ./client_emulated.sh
    context: ./app-debug.apk

  - name: anbox
    memory_mb: 4096
    cpus: 2
    disk:
      cloud_image:
        name: ubuntu_18_04
        expand_gigabytes: 15
    interfaces:
      - bridge: br0
    run_script: ./client_anbox.sh
    context: ./app-debug.apk

bridges:
  - name: br0
    connect_external_interfaces: [eth0]
    enable_dhcp_client: true
    controller: tcp:127.0.0.1:6653
    protocol: OpenFlow13

ssh_public_key: ___
