machines:
  - name: backend
    disk:
      cloud_image:
        name: ubuntu_18_04
    interfaces:
      - bridge: br0
    run_script: ./backend.sh

bridges:
  - name: br0
    connect_external_interfaces: [eth0]
    enable_dhcp_client: true

ssh_public_key: ___
