## template: jinja
#cloud-config
chpasswd:
  list: |
    nocloud:password
  expire: False
users:
  - name: nocloud
    gecos: nocloud
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh-authorized-keys:
      - {{ ds.meta_data.public_ssh_key }}
runcmd:
  - mkdir -p /etc/nocloud/
  - cloud-init query ds.meta_data.run_script > /etc/nocloud/run_script.sh
  - chmod +x /etc/nocloud/run_script.sh
  - /etc/nocloud/run_script.sh &> /etc/nocloud/run_script_log.txt


