## template: jinja
#cloud-config
chpasswd:
  list: |
    nocloud:password
  expire: False
users:
  - name: nocloud
    gecos: nocloud
    shell: /bin/bash
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh-authorized-keys:
      - {{ ds.meta_data.public_ssh_key }}
runcmd:
  - mkdir -p /etc/nocloud/context
  - cloud-init query ds.meta_data.run_script > /etc/nocloud/run_script.sh
  - chmod +x /etc/nocloud/run_script.sh
  - mkdir /nocloudtmp
  - mount /dev/sr0 /nocloudtmp
  - tar -xf /nocloudtmp/context.tar -C /etc/nocloud/context
  - umount /nocloudtmp
  - rm -rf /nocloudtmp
  - /etc/nocloud/run_script.sh > /etc/nocloud/run_script_out.txt 2>/etc/nocloud/run_script_err.txt


